### get price by day
curl --location 'http://localhost:3000/stock/byday?stockTicker=AAU'

### Get current price
curl --location 'http://localhost:3000/stock/realtimeprice?stockTicker=ROKU'

### get all current price
curl --location 'http://localhost:3000/stock/realtimepriceall'

### Get ticker news
curl --location 'http://localhost:3000/stock/news?stockTicker=ROKU'

### Get list ticker for type ahead
curl --location 'http://localhost:3000/stock/searchlist?stockTicker=AA'

### Get divident
curl --location 'http://localhost:3000/stock/dividends?stockTicker=T'