###
@rootUrl = http://localhost:3000

###Get New form  news-alpha-vantage
curl --location '{{rootUrl}}/stock/news-v2?stockTicker=BABA'

###Get New form  //news-stock-data
curl --location '{{rootUrl}}/stock/news-v3?stockTicker=AAL&date=2023-11-18'

###Get New form  //news-stock-data
curl --location '{{rootUrl}}/stock/news-v3?stockTicker=AAL&date=2023-11-17&type=24'

#### FIREBASE ALL
{{rootUrl}}/stock/news-fball/stockSDnews?stockTicker=ZM

#### FIREBASE ALL
{{rootUrl}}/stock/news-fball/stockAVnews?stockTicker=T

###FIREBASE day 
GET {{rootUrl}}/stock/news-fb/stockAVnews?stockTicker=T&date=2023-11-20

#### FIREBASE day
GET {{rootUrl}}/stock/news-fb/stockSDnews?stockTicker=T&date=2023-11-20


####
curl --location --request GET '{{rootUrl}}/stock/realtimefb-multiple/watchlists'

###Patch
PATCH /stock/realtimefb-multiple/watchlists HTTP/1.1
User-Agent: vscode-restclient
Content-Type: application/json
Host: localhost:3000
Content-Length: 490

{ "data":[ { "symbol": "DE", "name": "Deere & Company", "price": 363.67, "pctChange": 0.6783, "change": 2.45, "dayLow": 360.87, "dayHigh": 364.17, "yearHigh": 450, "yearLow": 345.55, "marketCap": 104737323670, "priceAvg50": 374.484, "priceAvg200": 393.17575, "exchange": "NYSE", "volume": 2059976, "avgVolume": 1568398, "open": 361.8, "previousClose": 361.22, "eps": 34.63, "pe": 10.5, "earnAnn": "2024-02-15T13:30:00.000+0000", "sharesOutstanding": 288001000, "timestamp": 1702069202 } ] }

####
curl --location --request GET '{{rootUrl}}/stock/realtimefb-multiple/gainers'





####
curl --location --request GET '{{rootUrl}}/stock/realtimefb-multiple/losers?date='


####
curl --location --request GET '{{rootUrl}}/stock/realtimefb-multiple/earncal?date=2023-12-10'

####------------------------------------------------------------------------------------------
#### FINNHUB
@newfhep = /fh
# @newfhep = 
### Get current price
# curl --location '{{rootUrl}}/stock/v2/realtimeprice?stockTicker=ROKU'
curl --location '{{rootUrl}}/stock{{newfhep}}/realtimeprice?stockTicker=ROKU'
### get insider transactions
curl --location '{{rootUrl}}/stock{{newfhep}}/insider-transactions?stockTicker=ROKU'

### get insider transactions
curl --location '{{rootUrl}}/stock{{newfhep}}/insider-transactions?stockTicker=ROKU'
### Get company profile
curl --location '{{rootUrl}}/stock{{newfhep}}/company-profile?stockTicker=aal'
###
{{rootUrl}}/stock/fh/earnings?end=2023-12-17
### Get ticker news for 5day
# curl --location '{{rootUrl}}/stock/news-v1?stockTicker=AAL'
### Get ticker news from 2023-01-11 to 2023-02-11
# curl --location '{{rootUrl}}/stock/news-v1?stockTicker=AAL&start=2023-01-11&end=2023-02-11'
curl --location '{{rootUrl}}/stock{{newfhep}}/news?stockTicker=AAL'
###
curl --location '{{rootUrl}}/stock{{newfhep}}/news?stockTicker=AAL&start=2023-01-11&end=2023-02-11'

####------------------------------------------------------------------------------------------
####POLYGON
@newpoep = /po
# @newpoep = 
### Get list ticker for type ahead
curl --location '{{rootUrl}}/stock{{newpoep}}/typeahead?stockTicker=BILL'

### Get divident
curl --location '{{rootUrl}}/stock{{newpoep}}/dividends?stockTicker=AAL'

### get price by day
curl --location '{{rootUrl}}/stock{{newpoep}}/byday?stockTicker=AAL'

####------------------------------------------------------------------------------------------
####FMP
@newfmep = /fm
### Get current price
curl --location '{{rootUrl}}/stock{{newfmep}}/realtimeprice?stockTicker=ROKU'
### get all current price
curl --location '{{rootUrl}}/stock{{newfmep}}/realtimepriceall'
### get multiple-company-prices
curl --location '{{rootUrl}}/stock{{newfmep}}/multiple-company-prices?stockTicker=ROKU,AAL,bill'
### Get losers
curl --location '{{rootUrl}}/stock{{newfmep}}/gainers-or-losers?stockMarket=losers'
### Get gainers
curl --location '{{rootUrl}}/stock{{newfmep}}/gainers-or-losers?stockMarket=gainers'
###
GET /stock{{newfmep}}/gainers-or-losers?stockMarket=gainers HTTP/1.1
Host: localhost:3000

### get all data for chart form Polygon
curl --location '{{rootUrl}}/stock/chartdata/day?stockTicker=ROKU&range=1&start=2023-01-11&end=2023-02-11&limit=20'

