### Sign IN
curl --location 'http://localhost:3000/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "test@gmail.com",
    "password": "fadfjloc"
}'

### Sign IN
curl --location 'http://localhost:3000/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "locprodstock33@gmail.com",
    "password": "Lock_for123!dotk"
}'
### signout
curl --location 'http://localhost:3000/auth/v2/signout'

###
# @userId = 66dbefd6-ff65-4b33-b2fc-24d0cda67518
@userId = a9d0075b-5270-405c-b76a-e0534319708e
@walletId = fdbf6ea1-0bb0-4116-8ddb-1041c28e4e23
### create user portfolio
curl --location 'http://localhost:3000/stock-portfolio/wallet' \
--header 'Content-Type: application/json' \
--data '{
    "id": "{{userId}}",
    "balance": 0
}'

### Get all user portfolios
GET http://localhost:3000/stock-portfolio/all

### Get Wallet
GET http://localhost:3000/stock-portfolio/wallet/{{userId}}

### Get Sells
GET http://localhost:3000/stock-portfolio/wallet/{{userId}}?type=sells

### post deposit "statusCode": 200
curl --location 'http://localhost:3000/stock-portfolio/submit' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "{{userId}}",
    "sPortfolioId":"{{walletId}}",
    "requestType":"deposit",
    "date": "2023-11-09",
    "amount": 100000,
    "method": "direct",
    "status":"complete"
}'

### post withdraw "statusCode": 200
curl --location 'http://localhost:3000/stock-portfolio/submit' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "{{userId}}",
    "sPortfolioId":"{{walletId}}",
    "requestType":"withdraw",
    "date": "2023-11-09",
    "amount": 1000,
    "method": "direct",
    "status":"complete"
}'

### post buy "statusCode": 200
curl --location 'http://localhost:3000/stock-portfolio/submit' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "{{userId}}",
    "sPortfolioId":"{{walletId}}",
    "requestType":"buy",
    "date": "2023-11-09",
    "symbol":"AALLS",
    "amount": 15,
    "matchPrice":7,
    "netvalue":105,
    "marketCap": null
}'

### post sell "statusCode": 200
curl --location 'http://localhost:3000/stock-portfolio/submit' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "{{userId}}",
    "sPortfolioId":"{{walletId}}",
    "requestType":"sell",
    "date": "2023-11-09",
    "symbol":"NCLH",
    "amount": 15,
    "matchPrice":7,
    "netvalue":105,
    "avaragePriceB":8,
    "netProfit":-15,
    "marketCap": 1000000000
}'
