### Sign IN
curl --location 'http://localhost:3000/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "test@gmail.com",
    "password": "fadfjloc"
}'


### create user portfolio
curl --location 'http://localhost:3000/stock-portfolio/wallet' \
--header 'Content-Type: application/json' \
--data '{
    "id": "66dbefd6-ff65-4b33-b2fc-24d0cda67518",
    "balance": 0
}'

### Get all user portfolios
GET http://localhost:3000/stock-portfolio/all

### Get user list 39a6072b-abc2-4092-921e-91aab42fa443
GET http://localhost:3000/stock-portfolio/wallet/66dbefd6-ff65-4b33-b2fc-24d0cda67518

### post deposit "statusCode": 200
curl --location 'http://localhost:3000/stock-portfolio/deposit' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "66dbefd6-ff65-4b33-b2fc-24d0cda67518",
    "sPortfolioId":"900cfcda-6703-4a17-a50e-b34484e99f5a",
    "dateDeposit": "2023-11-09",
    "amount": 1000,
    "method": "direct",
    "status":"complete"
}'

### post withdraw "statusCode": 200
curl --location 'http://localhost:3000/stock-portfolio/withdraw' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "66dbefd6-ff65-4b33-b2fc-24d0cda67518",
    "sPortfolioId":"900cfcda-6703-4a17-a50e-b34484e99f5a",
    "dateWithdraw": "2023-11-09",
    "amount": 1000,
    "method": "direct",
    "status":"complete"
}'

### post buy "statusCode": 200
curl --location 'http://localhost:3000/stock-portfolio/buy' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "66dbefd6-ff65-4b33-b2fc-24d0cda67518",
    "sPortfolioId":"900cfcda-6703-4a17-a50e-b34484e99f5a",
    "dateBuy": "2023-11-09",
    "symbol":"AAL",
    "amount": 1000,
    "matchPrice":14.12,
    "marketCap": 1000000000
}'

### post withdraw "statusCode": 200
curl --location 'http://localhost:3000/stock-portfolio/sell' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "66dbefd6-ff65-4b33-b2fc-24d0cda67518",
    "sPortfolioId":"900cfcda-6703-4a17-a50e-b34484e99f5a",
    "dateSell": "2023-11-09",
    "symbol":"AAL",
    "amount": 1000,
    "matchPrice":15.12,
    "marketCap": 1000000000
}'
