### create a new user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "te2st@gmail.com",
    "password": "fadfjloc"
}

### Sign in
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "te2st@gmail.com",
    "password": "fadfjloc"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### SignOut
POST  http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/8

### Find all users with a fiven email
GET  http://localhost:3000/auth/?email=ll@gmail.com

### Find all users
GET  http://localhost:3000/auth
### Delete a user given Id
DELETE http://localhost:3000/auth/7

### Update a user 2
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "aaaa@gmail.com"
}

### Sent email
POST  http://localhost:3000/sent


####
curl -X 'GET' \
  'http://localhost:3000/shop/products/types' \
  -H 'accept: */*'