### Get all user
GET http://localhost:3000/user

### Get user 1
GET http://localhost:3000/user/1

### Post User
curl --location 'http://localhost:3000/user' \
--header 'Content-Type: application/json' \
--data-raw '{"email":"ll@gmail.com","password":"132fasd"}'
