### Sign IN
curl --location 'http://localhost:3000/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "test@gmail.com",
    "password": "fadfjloc"
}'


### create user list
curl --location 'http://localhost:3000/stock-user/user-list' \
--header 'Content-Type: application/json' \
--data '{
    "id": "c0ad60b4-e391-429a-8571-f77f1a8cc5fd",
    "listTickers": ["AAL","NCLH"]
}'

### Get all user-lists
GET http://localhost:3000/stock-user/all-lists


### Get all all-watchlists
GET http://localhost:3000/stock-user/all-watchlists

### Delete
curl --location --request DELETE 'http://localhost:3000/stock-user/user-list/dfdc004a-2ca9-49ef-b42e-fa1045586121'

###
curl --location --request DELETE 'http://localhost:3000/stock-user/watchlist/f776cf8e-4fa2-481b-a785-cd1f35dd282a'
### post watchlist
curl --location 'http://localhost:3000/stock-user/watchlist' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "c0ad60b4-e391-429a-8571-f77f1a8cc5fd",
    "stockUserId":"b19c792e-5840-4d87-9adc-1769c8a617c6",
    "dateAdded": "2023-11-09",
    "pctChangeAtAdded": -1.5981,
    "priceAtAdded": 62.19,
    "symbol":"BILL",
    "spotline":false
}'

### post watchlist FANG
curl --location 'http://localhost:3000/stock-user/watchlist' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "c0ad60b4-e391-429a-8571-f77f1a8cc5fd",
    "stockUserId":"b19c792e-5840-4d87-9adc-1769c8a617c6",
    "dateAdded": "2023-11-09",
    "pctChangeAtAdded": -1.7759,
    "priceAtAdded": 155.97,
    "symbol":"FANG"
}'