### Sign IN
curl --location 'http://localhost:3000/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "test@gmail.com",
    "password": "fadfjloc"
}'

###
@userId = 66dbefd6-ff65-4b33-b2fc-24d0cda67518
@watchlistID = 0b91cc82-41c6-409b-b25b-4d2504457c22
### create user list
curl --location 'http://localhost:3000/stock-user/user-list' \
--header 'Content-Type: application/json' \
--data '{
    "id": "{{watchlistID}}",
    "listTickers": ["AAL","NCLH"]
}'

### update this list
curl --location --request PATCH 'http://localhost:3000/stock-user/user-list/{{userId}}' \
--header 'Content-Type: application/json' \
--data '{
     "listTickers": ["DDE"], "maxLists":10
}'
###
@list = 78a5e1fb-5568-4110-b3c7-684bf9d0cdc9
### Get Update 35d471c6-c637-46f2-a222-1549c789985f
GET http://localhost:3000/stock-user/user-list/{{userId}}

### Delete watchlist
curl --location --request DELETE 'http://localhost:3000/stock-user/watchlist/{{userId}}/{{list}}'

### Sign IN
curl --location 'http://localhost:3000/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "test1@gmail.com",
    "password": "fadfjloc"
}'


### create user list
curl --location 'http://localhost:3000/stock-user/user-list' \
--header 'Content-Type: application/json' \
--data '{
    "id": "bd8d3955-dc5c-471f-971b-67635f563412",
    "listTickers": ["AAL","NCLH"]
}'

### Get all user-lists
GET http://localhost:3000/stock-user/all-lists

### Get all user-listTickers
GET http://localhost:3000/stock-user/all-listTickers

### Get all all-watchlists
GET http://localhost:3000/stock-user/all-watchlists

### Get user list 35d471c6-c637-46f2-a222-1549c789985f
GET http://localhost:3000/stock-user/user-list/35d471c6-c637-46f2-a222-1549c789985f


### Get user list 39a6072b-abc2-4092-921e-91aab42fa443
GET http://localhost:3000/stock-user/user-list/39a6072b-abc2-4092-921e-91aab42fa443

### Get user list e1240614-ea62-4815-a264-a9b7fb531c3c of NEW USER "statusCode": 404,=> call create userlist
GET http://localhost:3000/stock-user/user-list/e1240614-ea62-4815-a264-a9b7fb531c3c


### Delete user-list 35d471c6-c637-46f2-a222-1549c789985f
curl --location --request DELETE 'http://localhost:3000/stock-user/user-list/35d471c6-c637-46f2-a222-1549c789985f'

### Delete user-list 39a6072b-abc2-4092-921e-91aab42fa443
curl --location --request DELETE 'http://localhost:3000/stock-user/user-list/39a6072b-abc2-4092-921e-91aab42fa443'

### Delete watchlist
curl --location --request DELETE 'http://localhost:3000/stock-user/watchlist/66dbefd6-ff65-4b33-b2fc-24d0cda67518/32bfd162-1fc1-4f51-b0d9-a0ad13827f2d'


### update watchlist
curl --location --request PATCH 'http://localhost:3000/stock-user/watchlist/{{userId}}/78a5e1fb-5568-4110-b3c7-684bf9d0cdc9' \
--header 'Content-Type: application/json' \
--data '{
    "dateAdded": "2023-11-09",
    "pctChangeAtAdded": -1.5981,
    "priceAtAdded": 62.19,
    "spotline":true
}'

### post watchlist "statusCode": 200
curl --location 'http://localhost:3000/stock-user/watchlist' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "{{userId}}",
    "stockUserId":"{{watchlistID}}",
    "dateAdded": "2023-11-09",
    "pctChangeAtAdded": -1.5981,
    "priceAtAdded": 62.19,
    "symbol":"BILLs",
    "spotline":false
}'



### update this list ADMIN ONLY
curl --location --request PATCH 'http://localhost:3000/stock-user/user-list/66dbefd6-ff65-4b33-b2fc-24d0cda67518' \
--header 'Content-Type: application/json' \
--data '{
     "listTickers": [
    "TWLO",
    "BABA"
  ], "maxLists":10
}'

### post watchlist AAL
curl --location 'http://localhost:3000/stock-user/watchlist' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "{{userId}}",
    "stockUserId":"{{watchlistID}}",
    "dateAdded": "2023-11-09",
    "pctChangeAtAdded": -1.7759,
    "priceAtAdded": 55.97,
    "symbol":"DEE"
}'

### Get Update 35d471c6-c637-46f2-a222-1549c789985f
GET http://localhost:3000/stock-user/user-list/{{userId}}
