### Sign IN
curl --location 'http://localhost:3000/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "test@gmail.com",
    "password": "fadfjloc"
}'


### create user list
curl --location 'http://localhost:3000/stock-user/user-list' \
--header 'Content-Type: application/json' \
--data '{
    "id": "c0ad60b4-e391-429a-8571-f77f1a8cc5fd",
    "listTickers": ["AAL","NCLH"]
}'

### update this list
curl --location --request PATCH 'http://localhost:3000/stock-user/user-list/c0ad60b4-e391-429a-8571-f77f1a8cc5fd' \
--header 'Content-Type: application/json' \
--data '{
    "listTickers": ["AAL","NO"]
}'

### Get Update c0ad60b4-e391-429a-8571-f77f1a8cc5fd
GET http://localhost:3000/stock-user/user-list/c0ad60b4-e391-429a-8571-f77f1a8cc5fd

### Sign IN
curl --location 'http://localhost:3000/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "test1@gmail.com",
    "password": "fadfjloc"
}'


### create user list
curl --location 'http://localhost:3000/stock-user/user-list' \
--header 'Content-Type: application/json' \
--data '{
    "id": "6cbc11b8-cc22-4a97-8f4f-0fe92b2fff7d",
    "listTickers": ["AAL","NCLH"]
}'

### Get all user-lists
GET http://localhost:3000/stock-user/all-lists

### Get all all-watchlists
GET http://localhost:3000/stock-user/all-watchlists

### Get user list c0ad60b4-e391-429a-8571-f77f1a8cc5fd
GET http://localhost:3000/stock-user/user-list/c0ad60b4-e391-429a-8571-f77f1a8cc5fd


### Get user list 6cbc11b8-cc22-4a97-8f4f-0fe92b2fff7d
GET http://localhost:3000/stock-user/user-list/6cbc11b8-cc22-4a97-8f4f-0fe92b2fff7d



### Delete user-list c0ad60b4-e391-429a-8571-f77f1a8cc5fd
curl --location --request DELETE 'http://localhost:3000/stock-user/user-list/c0ad60b4-e391-429a-8571-f77f1a8cc5fd'

### Delete user-list 6cbc11b8-cc22-4a97-8f4f-0fe92b2fff7d
curl --location --request DELETE 'http://localhost:3000/stock-user/user-list/6cbc11b8-cc22-4a97-8f4f-0fe92b2fff7d'

### Delete watchlist
curl --location --request DELETE 'http://localhost:3000/stock-user/watchlist/c0ad60b4-e391-429a-8571-f77f1a8cc5fd/9f0a85d0-8ad2-4fc2-b650-0ebe72aa64f2'


### update watchlist
curl --location --request PATCH 'http://localhost:3000/stock-user/watchlist/c0ad60b4-e391-429a-8571-f77f1a8cc5fd/4dcf22eb-9359-4fc2-93db-8adfe270d279' \
--header 'Content-Type: application/json' \
--data '{
    "dateAdded": "2023-11-09",
    "pctChangeAtAdded": -1.5981,
    "priceAtAdded": 62.19,
    "symbol":"BILL",
    "spotline":true
}'


### post watchlist
curl --location 'http://localhost:3000/stock-user/watchlist' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "c0ad60b4-e391-429a-8571-f77f1a8cc5fd",
    "stockUserId":"e8bd3075-ba07-4c82-b358-2a4af951a612",
    "dateAdded": "2023-11-09",
    "pctChangeAtAdded": -1.5981,
    "priceAtAdded": 62.19,
    "symbol":"BILL",
    "spotline":false
}'

### post watchlist FANG
curl --location 'http://localhost:3000/stock-user/watchlist' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "6cbc11b8-cc22-4a97-8f4f-0fe92b2fff7d",
    "stockUserId":"42b25434-47a6-44d3-b4e1-74ad8a445637",
    "dateAdded": "2023-11-09",
    "pctChangeAtAdded": -1.7759,
    "priceAtAdded": 155.97,
    "symbol":"FANG"
}'