###
@rootUrl = http://localhost:3000
# @rootUrl = https://my-api-all.adaptable.app
# @rootUrl = https://email-api-kuku20.onrender.com
# https://email-api-kuku20.onrender.com
### Sign IN
curl --location '{{rootUrl}}/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "locprodstock33@gmail.com",
    "password": "Lock_for123!dotk"
}'

### signout
curl --location '{{rootUrl}}/auth/v2/signout'

### Sign IN
curl --location '{{rootUrl}}/ai-tool/gemini' \
--header 'Content-Type: application/json' \
--data-raw '{
    "message": "I give the data on share prices over today, write a report of no more than 400 words describing the stocks performance and recommending whether to buy, hold or sell:",
    "data": [
        {
            "date": "2024-10-07 10:24:00",
            "open": 253.04,
            "low": 252,
            "high": 253.46,
            "close": 252.775,
            "volume": 8569
        },
        {
            "date": "2024-10-07 10:23:00",
            "open": 253.04,
            "low": 252,
            "high": 253.46,
            "close": 252.775,
            "volume": 8569
        }
    ]
}'

### Sign IN
curl --location '{{rootUrl}}/ai-tool/get-advice' \
--header 'Content-Type: application/json' \
--data-raw '{
    "message": "I give the data on share prices over today, write a report of no more than 100 words describing the stocks performance and recommending whether to buy, hold or sell:",
    "limit":"5000",
    "ticker":"QQQ",
    "range":"4hour",
    "start":"2024-10-07",
    "end":"2024-10-08",
    "type":"guess"
}'


### test with out aaa guess
curl --location 'http://localhost:3000/ai-tool/fb/guess/qqq'

###
fetch("https://email-api-kuku20.onrender.com/ai-tool/get-advice", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9,la;q=0.8,zh-CN;q=0.7,zh;q=0.6,vi;q=0.5",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "sec-ch-ua": "\"Google Chrome\";v=\"129\", \"Not=A?Brand\";v=\"8\", \"Chromium\";v=\"129\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "http://localhost:4200/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"type\":\"recommending\",\"message\":\"I give the data on share prices over today, write a report of no more than 500 words describing the stocks performance and recommending whether to buy, hold or sell:\",\"limit\":\"5000\",\"ticker\":\"DJT\",\"range\":\"1min\",\"start\":\"2024-06-13\",\"end\":\"2024-10-11\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});

### test with out aaa
curl --location 'http://localhost:3000/ai-tool/melu'
