### validation 
curl --location 'http://localhost:3000/auth/v2/signup' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "testtrue@gmail.com",
    "password": "fadfjloc",
    "displayName":"2Loc"
}'

### validation add ed
curl --location 'http://localhost:3000/auth/v2/signup' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "locprodstock33@gmail.com",
    "password": "Lock_for123!dotk",
    "displayName":"2Loc",
    "isAdmin": true
}'


### Sign IN
curl --location 'http://localhost:3000/auth/v2/signin' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "bob2@test.com",
    "password": "Pa$$w0rd",
    "isAdmin": true
}'

### test with out aaa
curl --location 'http://localhost:3000/auth/v2/me'

### signout
curl --location 'http://localhost:3000/auth/v2/signout'